---
sidebar: sidebar 
permalink: install-setup/initialize-ontap-cluster.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30 initialize cluster, set up cluster, ontap 
summary: 瞭解如何使用系統管理員在 ASA R2 系統上設定 ONTAP 叢集。 
searchtitle: 使用 ONTAP 系統管理員 | ASA R2 設定 ONTAP 叢集 
---
= 在 ASA R2 儲存系統上設定 ONTAP 叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 系統管理員會引導您快速輕鬆地完成 ONTAP ASA R2 叢集的設定工作流程。

在叢集設定期間、系統會建立預設的資料儲存虛擬機器（ VM ）。您也可以選擇啟用網域名稱系統（ DNS ）來解析主機名稱、將叢集設定為使用網路時間傳輸協定（ NTP ）進行時間同步、以及啟用靜態資料的加密。

.開始之前
收集下列資訊：

* 叢集管理IP位址
+
叢集管理 IP 位址是叢集管理員用來存取管理儲存 VM 及管理叢集的叢集管理介面唯一的 IPv4 位址。您可以向負責指派組織IP位址的管理員取得此IP位址。

* 網路子網路遮罩
+
在叢集設定期間、 ONTAP 會建議一組適合您組態的網路介面。如有必要、您可以調整建議。

* 網路閘道 IP 位址
* 合作夥伴節點 IP 位址
* DNS網域名稱
* DNS 名稱伺服器 IP 位址
* NTP 伺服器 IP 位址
* 資料子網路遮罩


.步驟
. 探索叢集網路
+
.. 將筆記型電腦連接到管理交換器、並存取網路電腦和裝置。
.. 開啟檔案總管。
.. 選擇 * 網路 * ；然後按一下滑鼠右鍵並選取 * 重新整理 * 。
.. 選取任一 ONTAP 圖示、然後接受畫面上顯示的任何憑證。
+
系統管理程式隨即開啟。



. 在 * 密碼 * 下、為管理帳戶建立強式密碼。
+
密碼長度必須至少八個字元、且必須包含至少一個字母和一個數字。

. 重新輸入密碼以確認、然後選擇 * 繼續 * 。
. 在 * 網路位址 * 下、輸入儲存系統名稱或接受預設名稱。
+
如果您變更預設的儲存系統名稱、新名稱必須以字母開頭、而且必須少於 44 個字元。您可以在名稱中使用句點（ . ）、連字號（ - ）或底線（ _ ）。

. 輸入叢集管理 IP 位址、子網路遮罩、閘道 IP 位址和合作夥伴節點的 IP 位址、然後選取 * 繼續 * 。
. 在 * 網路服務 * 下、選擇想要的選項 * 使用網域名稱系統（ DNS ）來解析主機名稱 * 、並 * 使用網路時間傳輸協定（ NTP ）來保持時間同步 * 。
+
如果您選擇使用 DNS 、請輸入 DNS 網域和名稱伺服器。如果您選擇使用 NTP 、請輸入 NTP 伺服器、然後選取 * 繼續 * 。

. 在 * 加密 * 下、輸入 Onboard Key Manager （ OKM ）的密碼。
+
預設會選取使用內建金鑰管理程式（ OKM ）加密靜止資料。如果您想要使用外部金鑰管理程式、請更新所選項目。

+
您也可以選擇在叢集設定完成後、將叢集設定為加密。

. 選擇 * 初始化 * 。
+
設定完成後、系統會將您重新導向至叢集的管理 IP 位址。

. 在 * 網路 * 下、選取 * 設定通訊協定 * 。
+
[cols="2"]
|===
| 若要設定 IP （ iSCSI 和 NVMe / TCP ）、請執行 ... | 若要設定 FC 和 NVMe / FC 、請執行 ... 


 a| 
.. 選擇 *IP* ；然後選擇 * 設定 IP 介面 * 。
.. 選取 * 新增子網路 * 。
.. 輸入子網路名稱、然後輸入子網路 IP 位址。
.. 輸入子網路遮罩、並選擇性地輸入閘道、然後選取 * 新增 * 。
.. 選取您剛建立的子網路、然後選取 * 儲存 * 。
.. 選擇*保存*。

 a| 
.. 選取 * FC* ；然後選取 * 設定 FC 介面 * 和 / 或 * 設定 NVMe / FC 介面 * 。
.. 選取 FC 和 / 或 NVMe / FC 連接埠、然後選取 * 儲存 * 。


|===
. 或者、下載並執行link:https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["ActiveIQ Config Advisor"]以確認您的組態。
+
ActiveIQ Config Advisor 是 NetApp 系統的工具、可檢查常見的組態錯誤。



.接下來呢？
您已準備好link:set-up-data-access.html["設定資料存取"]從 SAN 用戶端到 ASA R2 系統。
