---
sidebar: sidebar 
permalink: install-setup/set-up-data-access.html 
keywords:  
summary:  
---
= 啟用從 SAN 主機到 ASA R2 儲存系統的資料存取
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要設定資料存取，您應該確定 SAN 用戶端上的關鍵參數和設定已正確設定，以便與 ONTAP 正常運作。如果您要為 VMware 環境提供儲存設備，您應該安裝 OTV 10.3 ，只需管理 ASA R2 儲存設備即可。



== 從 SAN 主機設定資料存取

從 SAN 主機設定 ASA R2 系統資料存取所需的組態、會因主機作業系統和傳輸協定而異。正確的組態對於最佳效能和成功的容錯移轉非常重要。

請參閱的 ONTAP SAN 主機文件link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["VMware vSphere SCSI 用戶端"^]、link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["VMware vSphere NVMe 用戶端"^]並link:https://docs.netapp.com/us-en/ontap-sanhost/overview.html["其他 SAN 用戶端"^]將主機正確設定為連線至 ASA R2 系統。



== 移轉 VMware 虛擬機器

如果您需要將 VM 工作負載從 ASA 儲存系統移轉至 ASA R2 儲存系統、 NetApp 建議您使用link:https://www.vmware.com/products/cloud-infrastructure/vsphere/vmotion["VMware vSphere VMotion"^]執行即時且不中斷營運的資料移轉。



== 從第三方儲存系統遷移數據

從ONTAP 9.17.1 開始，您可以使用外部 LUN 匯入 (FLI) 將資料從第三方儲存系統上的 LUN 遷移到ASA r2 系統。使用 FLI 進行資料遷移可以幫助您降低遷移過程中資料遺失和停機的風險。

FLI 支援線上和離線遷移。在線上遷移中，客戶端系統保持在線，同時將資料從第三方儲存系統複製到ONTAP儲存系統。 Windows、Linux 和 ESXi 主機作業系統支援線上遷移。在離線遷移中，客戶端系統處於離線狀態，LUN 資料從第三方儲存系統複製到ONTAP儲存系統，然後客戶端系統重新處於線上狀態。

* 學習如何執行link:https://docs.netapp.com/us-en/ontap-fli/san-migration//concept_fli_offline_workflow.html["FLI 離線遷移"^] 。
* 學習如何執行link:https://docs.netapp.com/us-en/ontap-fli/san-migration//concept_fli_online_workflow.html["FLI 線上遷移"^] 。




== 將 ASA R2 系統設定為 VMware 環境中的儲存供應商

您可以使用適用於 VMware 的 ONTAP 工具，輕鬆將 ASA R2 系統啟用為 VMware 環境中的儲存供應商。

適用於 VMware vSphere 的 ONTAP 工具是一組與 VMware vCenter Server 虛擬應用裝置（ vCSA ）搭配使用的工具，可輕鬆管理 VMware ESXi 主機上的虛擬機器。

ASA R2 系統受及更新版本支援link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/concepts/ontap-tools-overview.html["適用於 VMware vSphere 10.3 的 ONTAP 工具"^]。

瞭解如何link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["部署適用於 VMware 的 ONTAP 工具"^]使用它來執行下列作業：

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["新增 vCenter Server 執行個體"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-esx-server-multipath-and-timeout-settings.html["設定 ESXi 主機設定"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/discover-storage-systems-and-hosts.html["探索您的 ASA R2 儲存系統和主機"^]


.接下來呢？
您已準備好link:../manage-data/provision-san-storage.html["配置儲存設備"]讓 SAN 主機讀取資料並將資料寫入儲存單元。
