---
sidebar: sidebar 
permalink: secure-data/respond-anti-ransomware-protection-alerts.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, arp/ai, alerts, respond, warnings, security 
summary: 查看潛在勒索軟體攻擊的警告並在系統管理員中採取行動。 
---
= 使用ASA r2 儲存系統上的 AI 警報來回應自主勒索軟體防護
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果人工智慧自主勒索軟體防護 (ARP/AI) 偵測到您的一個或多個ASA r2 系統儲存單元存在異常活動，系統管理員儀表板上會產生警告。您應該查看警告，驗證活動，並在必要時採取措施阻止任何對您資料的潛在威脅。

如果顯示 ARP/AI 警告訊息，在採取措施之前，您應該使用適當的應用程式完整性檢查器來驗證儲存單元上資料的完整性。驗證儲存單元的資料完整性有助於您確定該活動是否可接受，或是否為潛在的勒索軟體攻擊。

[cols="2,2"]
|===
| 如果出現異常活動... | 然後這樣做... 


| 可接受 | 將該活動標記為誤報。 


| 潛在的勒索軟體攻擊 | 將該活動標記為潛在的勒索軟體攻擊。 


| 不定 | 請勿立即採取措施。請監控儲存單元最多 7 天。如果儲存單元繼續正常運行，則將該活動標記為誤報。如果儲存單元繼續表現出異常活動，則將該活動標記為潛在的勒索軟體攻擊。 
|===
.步驟
. 在System Manager中、選取* Dashboard *。
+
如果 ARP 在一個或多個儲存單元上偵測到異常活動，則會在 *警告* 下顯示一則訊息。

. 選擇警告訊息。
. 在「事件概覽」下，選擇指示具有異常活動的儲存單元數量的「警告」訊息。
. 在*具有異常活動的儲存單元*下，選擇儲存單元。
. 選擇*安全*。
+
如果儲存單元上存在異常活動，則會在「反勒索軟體」下方顯示一則訊息。

. 選擇“*選擇一個操作*”。
. 選擇*標記為誤報*或選擇*標記為潛在勒索軟體攻擊*。


.接下來呢？
如果您發現儲存單元活動出現激增，無論是單次激增還是某種新常態下的激增，都應將其報告為安全狀態。手動將這些激增報告為安全狀態有助於提高 ARP 威脅評估的準確性。了解如何link:https://docs.netapp.com/us-en/ontap/anti-ransomware/manage-parameters-task.html#report-known-surges["報告已知的 ARP/AI 激增"^]。
