---
sidebar: sidebar 
permalink: learn-more/hardware-comparison.html 
keywords: compare asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, hardware comparison, asa r2 
summary: ASA 系統提供專為僅 SAN 解決方案最佳化的硬體支援。ASA R2 系統提供硬體與軟體的最佳化。 
searchtitle: 比較 ASA R2 系統與其他 ONTAP 系統 
---
= 比較 ASA R2 系統與其他 ONTAP 系統
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2 系統為基於全快閃平台建置的純 SAN 環境提供硬體和軟體解決方案。 ASAr2 系統與其他ONTAP系統（ ASA 、 AFF和FAS）在ONTAP特性、儲存層和支援協定的實作方面有所不同。

下列 ASA 平台歸類為 ASA R2 系統：

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30




== 性格差異

在 ASA R2 系統上、 ONTAP 軟體經過簡化、可支援重要的 SAN 功能、同時限制非 SAN 相關功能的可見度和可用度。例如、在 ASA R2 系統上執行的系統管理員不會顯示為 NAS 用戶端建立主目錄的選項。此精簡版的 ONTAP 被識別為 ASA R2 特性 _ 。在 ASA 系統上執行的 ONTAP 會識別為 ASA ONTAP 特性設定 _ 。在 AFF 和 FAS ONTAP 系統上執行的 ONTAP 被識別為 _ 統一化 ONTAP 特性 _ 。ONTAP 命令參考（手冊頁）、 REST API 規格和 EMS 訊息（若適用）中會參考 ONTAP 特性之間的差異。

您可以從系統管理員或 ONTAP CLI 驗證 ONTAP 儲存設備的特性設定。

* 從 System Manager （系統管理器）菜單中，選擇 *Cluster （羣集） > Overview （概述） * 。
* 從 CLI 輸入： `system node show -personality -is-disaggregated`


對於ASA r2 系統，_personality_ 為 _ASA r2_，且 _is-disaggregated_ 的狀態為 _true_。

ONTAP 儲存系統的特性設定無法變更。



== 儲存層差異

ASA r2 系統使用簡化的儲存層，該儲存層與FAS、 AFF和ASA系統所使用的儲存層不同。

.FAS、 AFF和ASA系統
FAS、 AFF和ASA系統的儲存層使用聚合作為基本儲存單元。聚合擁有儲存系統中可用的一組特定磁碟。聚合將其擁有的磁碟上的空間分配給 LUN 和命名空間的磁碟區。使用這些系統， ONTAP使用者可以建立和修改聚合、磁碟區、LUN 和命名空間。

.ASA r2 系統
ASA r2 系統中的儲存層使用儲存可用區，而非聚合。儲存可用區是單一 HA 對的兩個節點均可存取的公共儲存池。 HA對中的兩個節點均可存取其共享儲存可用區中的所有可用磁碟。例如，在雙節點ASA r2 系統ONTAP叢集中，有一個儲存可用區，叢集中的兩個節點均可存取。在四節點ASA r2 系統ONTAP叢集中，有兩個儲存可用區。叢集中的每個 HA 對都可以存取其中一個儲存可用區。

建立儲存單元（基於 LUN 或 NVMe 命名空間）時， ONTAP會自動在對應的儲存可用區中建立一個磁碟區來容納該儲存單元。新建立的磁碟區將自動放置在該儲存可用區內，以實現最佳效能和均衡的容量利用率。根據您的ONTAP版本， ASA r2 系統還支援跨儲存可用區自動重新平衡儲存單元，以及在 HA 對中的節點之間自動重新平衡工作負載。

* 自動儲存單元重新平衡
+
從ONTAP 9.16.1 開始，如果儲存單元的增加或減少導致整個儲存可用區域的儲存利用率不平衡，則ONTAP會根據需要自動移動儲存單元以重新平衡利用率並最佳化效能。

* 自動工作負載重新平衡
+
從ONTAP 9.17.1 開始， ONTAP會自動在ASA r2 系統 HA 對中的節點之間重新平衡工作負載，以達到最佳效能。例如，如果節點的使用率增加到 70%，而其 HA 配對節點的使用率僅為 30%，則ONTAP會自動調整工作負載，以使每個節點的使用率更接近。由於 HA 對中的節點共享相同的儲存可用區，因此工作負載重新平衡是一種無副本操作，不會對效能產生任何影響。升級到ONTAP 9.17.1 或初始化新的ONTAP 9.17.1 ASA r2 叢集 14 天后，預設啟用自動工作負載重新平衡功能。您可以link:../administer/rebalance-workloads.html["更改預設設定"]啟用或停用自動工作負載重新平衡，或將其設為建議狀態以標記不平衡的工作負載而不自動移動它們。





== ASA R2 系統差異摘要

ASA r2 系統與FAS、 AFF和ASA系統有以下不同：

[cols="1h,2,2,2,2"]
|===
|  | ASA r2 | ASA | AFF | FAS 


 a| 
* ONTAP 特性 *
| ASA r2 | ASA | 統一化 | 統一化 


 a| 
* SAN 傳輸協定支援 *
| 是的 | 是的 | 是的 | 是的 


 a| 
* NAS 傳輸協定支援 *
| 否 | 否 | 是的 | 是的 


 a| 
* 儲存層支援 *
| 儲存可用性區域 | 集合體 | 集合體 | 集合體 
|===
由於這種自動化且簡化的儲存管理方法，某些 System Manager 選項、 ONTAP指令和 REST API 端點在ASA r2 系統上不可用或使用受限。例如，由於ASA r2 系統的磁碟區建立和管理是自動化的，因此「磁碟區」功能表不會顯示在 System Manager 中，且 `volume create`命令不受支援。link:cli-support.html["了解有關不受支援的ASA r2 命令的更多信息"] 。

以下說明 ASA R2 系統與 ONTAP 、 AFF 和 ASA 系統之間與 FAS 命令列介面（ CLI ）和 REST API 相關的主要差異。

.使用傳輸協定服務建立預設 SVM
新叢集會自動包含已啟用 SAN 傳輸協定的預設資料 SVM 。IP 資料生命安全裝置支援 iSCSI 和 NVMe / TCP 傳輸協定、並 `default-data-blocks`依預設使用服務原則。

.自動建立 Volume
建立儲存單元（ LUN 或命名空間）會自動從儲存可用區域建立磁碟區。這會產生一個簡化且通用的命名空間。刪除儲存單元會自動刪除相關的磁碟區。

.精簡與完整資源配置的變更
ASA R2 儲存系統上的儲存單元一律會精簡佈建。不支援完整資源配置。

.資料壓縮的變更
對溫度敏感的儲存效率不適用於 ASA R2 系統。在 ASA R2 系統上、壓縮並非以 _hot_ （經常存取）資料或 _cold （不常存取）資料為基礎。壓縮開始時、不會等到資料變冷。

.以取得更多資訊
* 深入瞭解 link:https://docs.netapp.com/us-en/ontap-systems-family/intro-family.html["ONTAP 硬體系統"^]。
* 請參閱中有關 ASA 和 ASA R2 系統的完整組態支援和限制link:https://hwu.netapp.com/["NetApp Hardware Universe"^]。
* 深入瞭解link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"^]。

