---
sidebar: sidebar 
permalink: learn-more/software-support-limitations.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa, a50, asa a30, asa a20, asa c30, unsupported features 
summary: 雖然 ASA R2 系統提供廣泛的 SAN 解決方案支援、但不支援某些 ONTAP 軟體功能。 
---
= ASA R2 儲存系統的 ONTAP 軟體支援與限制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
雖然 ASA R2 系統提供廣泛的 SAN 解決方案支援、但不支援某些 ONTAP 軟體功能。

.ASA R2 系統不支援下列項目：
* FabricPool
* LUN 密集資源配置
* MetroCluster
* NetApp Aggregate Encryption （NAE）
* 物件傳輸協定
* ONTAP S3 SnapMirror 和 S3 API
* SnapLock
+
SnapLock Compliance 和 Enterprise 模式不支援 SAN 環境中的主叢集。SnapLock for SnapVault 支援二線系統叢集。

* SnapMirror複製在ASA r2 系統上受支持，但有以下限制：
+
** 不支援SnapMirror同步複製。
** SnapMirror非同步複製僅支援在兩個ASA r2系統之間進行。SnapMirror非同步複製不支援在ASA r2 系統與ASA、 AFF或FAS系統或雲端之間進行。
+
詳細了解link:../data-protection/pre-defined-protection-policies.html["ASA r2 系統支援SnapMirror複製策略"]。

** SnapMirror主動同步僅支援在兩個ASA r2 系統之間進行。
+
詳細了解link:../data-protection/snapmirror-active-sync.html["ASA r2 系統上的SnapMirror主動同步"]。





.ASA R2 系統支援下列項目：
* 雙層加密
+
ASA r2 系統支援使用自加密磁碟機 (SED) 的硬體加密和使用 NetApp 磁碟區加密 (NVE) 技術的軟體加密。link:../secure-data/encrypt-data-at-rest.html["瞭解如何套用雙層加密"] 以保護 ASA r2 系統上的資料。



.以取得更多資訊
* 如link:https://hwu.netapp.com/["NetApp Hardware Universe"^]需 ASA R2 硬體支援與限制的詳細資訊、請參閱。

