---
sidebar: sidebar 
permalink: learn-more/software-support-limitations.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa, a50, asa a30, asa a20, asa c30, unsupported features 
summary: 雖然 ASA R2 系統提供廣泛的 SAN 解決方案支援、但不支援某些 ONTAP 軟體功能。 
---
= ASA R2 儲存系統的 ONTAP 軟體支援與限制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
雖然 ASA R2 系統提供廣泛的 SAN 解決方案支援、但不支援某些 ONTAP 軟體功能。

.ASA R2 系統不支援下列項目：
* 預設自動 iSCSI LIF 容錯移轉
+
在 ASA R2 系統中，預設的網路 LIF 會在 NVMe 和 SCSI 主機之間共用，因此不支援自動容錯移轉。若要啟用自動 iSCSI LIF 容錯移轉link:../administer/manage-client-vm-access.html#create-a-lif-network-interface["建立僅 iSCSI LIF"]，您必須。依預設，自動容錯移轉僅在 iSCSI 上啟用。

+
啟用自動 iSCSI LIF 容錯移轉時，如果發生儲存容錯移轉， iSCSI LIF 會自動從其主節點或連接埠移轉至其 HA 合作夥伴節點或連接埠，然後在容錯移轉完成後再移回。或者，如果 iSCSI LIF 的連接埠變得不正常， LIF 會自動移轉至目前主節點的健全連接埠，然後在連接埠再次正常運作時，再移回原始連接埠。

* FabricPool
* LUN 密集資源配置
* MetroCluster
* 物件傳輸協定
* ONTAP S3 SnapMirror 和 S3 API


.ASA R2 系統支援下列項目：
* SnapLock
+
link:../secure-data/ransomware-protection.html["瞭解如何鎖定快照"]在您的 ASA R2 系統上。

* 雙層加密
+
link:../secure-data/encrypt-data-at-rest.html["瞭解如何套用雙層加密"]ASA R2 系統上的資料。





== 支援SnapMirror複製

SnapMirror複製在ASA r2 系統上受支持，但有以下限制：

* 不支援SnapMirror同步複製。
* SnapMirror主動同步僅支援在兩個ASA r2 系統之間進行。
* SnapMirror非同步複製僅支援在兩個ASA r2系統之間進行。SnapMirror非同步複製不支援在ASA r2 系統與ASA、 AFF或FAS系統或雲端之間進行。
+
詳細了解link:data-protection/pre-defined-protection-policies.html["ASA r2 系統支援SnapMirror複製策略"]。



.以取得更多資訊
* 如link:https://hwu.netapp.com/["NetApp Hardware Universe"^]需 ASA R2 硬體支援與限制的詳細資訊、請參閱。

