---
sidebar: sidebar 
permalink: administer/increase-storage-capacity.html 
keywords: increase, capacity, node, shelf, drive, expand, storage, asa r2, asa r2, asa a1k, asa 70, asa 90 
summary: 將磁碟機新增至節點或機櫃、以增加 ASA R2 儲存單元的容量。 
---
= 增加 ASA R2 儲存系統的儲存容量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將磁碟機新增至節點或機櫃、以增加 ASA R2 系統的儲存容量。



== 使用 NetApp Hardware Universe 準備安裝新磁碟機

在將新磁碟機安裝到節點或機櫃之前、請先使用 NetApp Hardware Universe 確認您要新增的磁碟機受到 ASA R2 平台的支援、並識別新磁碟機的正確插槽。新增磁碟機的正確插槽視平台機型和ONTAP 版本而定。在某些情況下、您需要依序將磁碟機新增至特定插槽。

.步驟
. 前往link:https://hwu.netapp.com/["NetApp Hardware Universe"^]。
. 在 * 產品 * 下、選取您的硬體組態。
. 選擇您的 ASA R2 平台。
. 選取您的 ONTAP 版本、然後選取 * 顯示結果 * 。
. 在圖形下方、選取 * 按一下此處以查看替代檢視 * 、然後選擇符合您組態的檢視。
. 使用組態檢視來確認新磁碟機是否受支援、以及安裝的正確插槽。


.結果
您已確認新磁碟機受到支援、而且您知道適當的安裝插槽。



== 在 ASA R2 上安裝新磁碟機

在單一程序中應新增的磁碟機數量下限為六個。新增單一磁碟機可能會降低效能。

.關於這項工作
您應該針對每個磁碟機重複本程序中的步驟。

.步驟
. 請妥善接地。
. 從平台正面輕移擋板。
. 將新磁碟機插入正確的插槽。
+
.. 在CAM握把處於開啟位置時、請用手插入新的磁碟機。
.. 推動直到磁碟機停止。
.. 合上CAM握把、讓磁碟機完全插入中間平面、並將握把卡入定位。
+
請務必緩慢關閉CAM握把、使其與磁碟機正面正確對齊。



. 確認磁碟機的活動LED（綠色）亮起。
+
** 如果 LED 持續亮起、表示磁碟機已通電。
** 如果 LED 閃爍、表示磁碟機已通電、而且 I/O 正在進行中。如果磁碟機韌體正在更新、 LED 也會閃爍。
+
磁碟機韌體會在沒有目前韌體版本的新磁碟機上自動更新（不中斷營運）。



. 如果您的節點已設定為磁碟機自動指派、您可以等待 ONTAP 自動將新磁碟機指派給節點。如果您的節點未設定為磁碟機自動指派、或是偏好的、您可以手動指派磁碟機。
+
新磁碟機必須指派給節點、才能被辨識。



.接下來呢？
識別新磁碟機之後、請確認已新增磁碟機、並正確指定其擁有權。
