---
sidebar: sidebar 
permalink: administer/space-balancing.html 
keywords: capacity, space, rebalancing, balanced, placement, balance, asa r2 
summary: 您可能需要重新命名節點、以符合組織的命名慣例或其他管理理由。 
---
= 了解ASA r2 叢集中的ONTAP容量均衡
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於ASA r2 系統， ONTAP使用 _均衡放置_ 將新建立的儲存單元自動放置在最佳儲存可用區，以實現最佳效能和均衡的儲存利用率。如果您執行的是ONTAP 9.17.1 或更高版本，則現有儲存單元所佔用的空間將使用_動態空間平衡_進行平衡。如果您正在執行ONTAP 9.16.1，則現有儲存單元所佔用的空間將使用基於副本的工作負載重新平衡進行平衡。

[cols="2"]
|===
| 功能 | 得到支持… 


| 均衡佈局 | ONTAP 9.16.1 及更高版本 


| 動態空間平衡 | ONTAP 9.17.1 及更高版本 


| 基於副本的工作負載重新平衡 | 僅限ONTAP 9.16.1 
|===
.均衡佈局
透過_均衡放置_，新建立的儲存單元會自動放置在最佳儲存可用區內，以達到最佳效能和均衡的儲存利用率。  ONTAP 9.16.1 及更高版本預設啟用均衡放置。

.動態空間平衡
透過動態空間平衡， ONTAP會主動監控叢集中的可用空間，並自動在儲存可用區內移動儲存單元，以維持空間利用率的平衡。如果群集範圍內的容量利用率達到 80%，則會自動發出 EMS 警告；如果達到 90%，則會自動發出 EMS 警報。

升級到ONTAP 9.17.1 或更高版本後 14 天，動態空間平衡功能將預設為啟用。如果您需要修改預設的 14 天啟用期，請聯絡NetApp支援。啟用動態空間平衡後，無法從ONTAP 9.17.1 回溯。

動態空間平衡根據叢集中所有節點可用空間的總體平均值（全域平均值）以_正常模式_或_低空間模式_運行。

* *普通模式*
+
在正常模式下， ONTAP每三分鐘檢查一次，以確定是否需要動態空間平衡。當滿足以下條件時，動態空間平衡功能以正常模式運作：

+
** 全球平均空隙率為 10% 或更高。
** 叢集中至少有一個節點的可用空間比全局平均水準要多。
** 叢集中至少有一個節點的可用空間比全域平均少 20%。


* *低空間模式*
+
在低空間模式下， ONTAP每分鐘檢查一次，以確定是否需要動態空間平衡。當滿足以下條件時，動態空間均衡以低空間模式運作：

+
** 全球平均自由空間不足10%。
** 叢集中至少有一個節點的可用空間比全局平均水準要多。
** 叢集中至少有一個節點的可用空間少於全域平均水準。




.基於副本的工作負載重新平衡
透過基於複製的工作負載重新平衡，如果儲存可用區內出現儲存利用率不平衡的情況， ONTAP會自動將造成不平衡的儲存單元複製到具有更大可用空間的儲存可用區。如果目標儲存可用區沒有足夠的可用空間， ONTAP將不會執行任何平衡操作。基於副本的工作負載重新平衡僅適用於執行ONTAP 9.16.1 的ASA r2 系統，並且預設在這些系統上啟用。在ONTAP 9.17.1 及更高版本中，它被動態空間平衡所取代。

如果您需要修改基於副本的工作負載重新平衡的預設設置，請聯絡NetApp支援。
