---
sidebar: sidebar 
permalink: get-started/learn-about.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, learn more, learn about, get started 
summary: ASA r2 系統（ASA A1K、A90、A70、A50、A30、A20、C30）提供統一的硬體和軟體解決方案，為僅限 SAN 的客戶提供簡化的體驗。 
searchtitle: 了解 ASA A1K、A90、A70、A50、A30 A20 和 C30 系統 
---
= 瞭解 ASA R2 儲存系統
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp ASA R2 系統提供統一化的硬體與軟體解決方案，可針對僅限 SAN 的客戶需求，提供簡化的體驗。

下列 ASA 平台歸類為 ASA R2 系統：

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30


ASA R2 系統支援所有 SAN 傳輸協定（ iSCSI ， FC ， NVMe / FC ， NVMe / TCP ）。iSCSI ， FC ， NVMe / FC 和 NVMe / TCP 傳輸協定支援對稱的雙主動式架構，可執行多重路徑，讓主機和儲存設備之間的所有路徑都處於主動 / 最佳化狀態。iSCSI 和 NVMe / TCP 傳輸協定支援主機和儲存設備之間的直接路徑。

在 ASA R2 系統上、 ONTAP 軟體和系統管理員經過簡化、可支援基本的 SAN 功能、同時移除 SAN 環境中不支援的功能。

ASA R2 系統採用一致性群組的儲存單元：

* _storage unit_ 可為 SAN 主機提供儲存空間以進行資料作業。儲存單元是指 SCSI 主機的 LUN 或 NVMe 主機的 NVMe 命名空間。
* _A Consistency group_ 是以單一單元管理的儲存單元集合。


ASA R2 系統使用儲存單元和一致性群組來簡化儲存管理和資料保護。例如，假設您的資料庫由一致性群組中的 10 個儲存單元組成，而您需要備份整個資料庫。您可以備份一致性群組來保護整個資料庫、而無需個別備份每個儲存單元。

為了保護您的資料免受盜竊或勒索軟體等惡意攻擊，ASA r2 系統支援板載金鑰管理器、雙層加密、多因素身份驗證和多管理員驗證。輔助 ASA r2 系統也支援防篡改快照。

ASA R2 系統不支援叢集混合搭配目前的 ASA 、 AFF 或 FAS 系統。

.以取得更多資訊
* 如link:https://hwu.netapp.com/["NetApp Hardware Universe"^]需ASA R2 系統支援與限制的詳細資訊，請參閱。
* 深入瞭解 link:../learn-more/hardware-comparison.html["ASA R2 系統與 ASA 系統的比較"]。
* 深入瞭解link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"]。

