---
sidebar: sidebar 
permalink: data-protection/manage-consistency-groups.html 
keywords: consistency groups, snapshots, data protection, protect data, add, remove, delete, storage units, lun, namespace, increase capacity 
summary: 使用一致性群組同時對多個儲存單元執行各種動作、而非在每個單元上個別執行動作。 
---
= 了解ASA r2 儲存系統上的ONTAP一致性組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
一致性組是作為單一單元進行管理的儲存單元的集合。使用一致性組簡化儲存管理。

例如，假設您有一個由一致性群組中的 10 個儲存單元組成的資料庫，並且您需要備份整個資料庫。您無需備份每個儲存單元，只需在一致性群組中新增快照資料保護即可備份整個資料庫。將儲存單元作為一致性群組而不是單獨備份也可以提供所有單元的一致備份，而單獨備份單元可能會造成不一致。

從ONTAP 9.16.1 開始，您可以使用系統管理員在ASA r2 系統上建立分層一致性群組。在層次結構中，一個或多個一致性組被配置為父一致性組下的子組。

階層式一致性群組可讓您將個別的快照原則套用到每個子一致性群組，並透過複寫父叢集，將所有子一致性群組的快照複寫到單一單元的遠端叢集。如此可簡化複雜資料結構的資料保護與管理。例如，假設您建立一個父一致性群組，稱為 `SVM1_app`，其中包含兩個子一致性群組： `SVM1app_data`應用程式資料和 `SVM1app_logs`應用程式記錄。每 15 分鐘拍攝一次的快照 `SVM1app_data`，每小時拍攝一次的快照 `SVM1app_logs`。父一致性群組具有 SnapMirror 原則， `SVM1_app,`可每 24 小時將和 `SVM1app_logs`的快照複寫 `SVM1app_data`到遠端叢集。父一致性群組 `SVM1_app`是以單一單位來管理，子一致性群組則以個別單位來管理。



== 複製關係中的一致性組

從ONTAP 9.17.1 開始，您可以對非同步複製關係或SnapMirror活動同步關係中的一致性群組進行以下幾何更改，而無需破壞或刪除該關係。當主一致性組上發生幾何變化時，該變化將複製到輔助一致性組。

* link:manage-consistency-groups-add-remove-storage-units.html["修改儲存單元的大小"]透過新增或刪除儲存單元。
* link:manage-hierarchical-consistency-groups.html#promote-an-existing-consistency-group-into-a-parent-consistency-group["提升單一一致性組"]到父一致性組。
* link:manage-hierarchical-consistency-groups.html#demote-a-parent-consistency-group-to-a-single-consistency-group["降級父一致性群組"]到單一一致性組。
* link:manage-hierarchical-consistency-groups.html#detach-a-child-consistency-group-from-a-parent-consistency-group["分離子一致性組"]來自父一致性群組。
* link:manage-hierarchical-consistency-groups.html#create-a-child-consistency-group["建立子一致性群組"]使用現有的一致性組。


在ONTAP 9.16.1 中，您必須link:snapmirror-active-sync-break-relationship.html["打破非同步複製關係"]和link:snapmirror-active-sync-delete-relationship.html["刪除SnapMirror活動同步關係"]在對一致性組進行幾何變更之前。
